[package]
name = "mm-config-namespace-config-validate"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
tivet-operation.workspace = true
chirp-client.workspace = true
prost = "0.10"

[dev-dependencies]
chirp-worker.workspace = true
