[package]
name = "team-validate"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
tivet-operation.workspace = true
chirp-client.workspace = true
prost = "0.10"

team-resolve-display-name.workspace = true

[dev-dependencies]
chirp-worker.workspace = true
