[package]
name = "telemetry-beacon"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
async-posthog.workspace = true
chirp-client.workspace = true
futures-util = "0.3"
indoc = "1.0"
lazy_static = "1.4"
prost = "0.10"
tivet-connection.workspace = true
tivet-operation.workspace = true
tivet-pools.workspace = true
tivet-runtime.workspace = true
tokio = { version = "1.40", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", default-features = false, features = [
    "fmt",
    "json",
    "ansi",
] }
tracing-logfmt = "0.3"

chirp-workflow.workspace = true
cloud-version-get.workspace = true
dynamic-config.workspace = true
game-get.workspace = true
game-namespace-get.workspace = true
game-version-get.workspace = true
mm-player-count-for-namespace.workspace = true
pegboard.workspace = true
tivet-config.workspace = true
tivet-env.workspace = true
serde = { version = "1.0.214", features = ["derive"] }
sysinfo = "0.32.0"
team-get.workspace = true
team-member-count.workspace = true

[dependencies.sqlx]
workspace = true

[dev-dependencies]
chirp-worker.workspace = true
chrono = "0.4"
