[package]
name = "chirp-metrics"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
tivet-metrics.workspace = true
lazy_static = "1.4"
