[package]
name = "external-worker"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
chirp-worker.workspace = true
chirp-client.workspace = true
reqwest = { version = "0.11" }
tivet-health-checks.workspace = true
tivet-metrics.workspace = true
tivet-runtime.workspace = true
chrono = "0.4"
tivet-config.workspace = true

[dev-dependencies]
chirp-worker.workspace = true
