[package]
name = "server-spec"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
chirp-workflow.workspace = true

linode.workspace = true
tivet-config.workspace = true
