[package]
name = "dynamic-config"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
chirp-workflow.workspace = true
indoc = "2.0.5"
tivet-config.workspace = true
tivet-operation.workspace = true
tokio = "1.40.0"
